services:

  # ==========================================================
  # POSTGRESQL
  # ==========================================================

  postgres:
    image: postgres:16-alpine
    container_name: pipelineiq-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5


  # ==========================================================
  # AIRFLOW
  # ==========================================================

  airflow:
    build:
      context: ./airflow

    container_name: pipelineiq-airflow
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

      # Pipeline database connection
      PIPELINE_DB_HOST: postgres
      PIPELINE_DB_PORT: "5432"
      PIPELINE_DB_NAME: ${POSTGRES_DB}
      PIPELINE_DB_USER: ${POSTGRES_USER}
      PIPELINE_DB_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "8080:8080"

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs

    command: standalone


volumes:
  postgres_data: